### ISSUE TITLE
Why did the experiment select the known class as the positive sample?

### ISSUE THREAD

**Issue by leyiweb** [guglielmocamporese/cvaecaposr#2]
I noticed that in the experimental code, you use known class as a positive sample to calculate related indicators. This does not seem to be consistent with the openset/ODD field. Most of the openset open source codes choose unknown class as a positive sample, such as the OSRCI method you compared.

**Comment by guglielmocamporese** [comment]
Hey,

thank you for your interest in our project. In general, it does not matter which class you decide to use as the positive class in a binary classification task. For the unknown detection problem is the same, you can decide to model either the known probability or the unknown probability of a particular input sample. Specifically, in our project, we considered the positive class as the "unknown" class, mapped as 0 (see the example below from our code, the `pos_label` variable)

```python
# cvaecaposr/models/cvaecaposr.py, line 461
def test_epoch_end(self, test_outputs):        
    auroc = pl.metrics.classification.AUROC(pos_label=0)        
    probs, y_ku = torch.cat(test_outputs, 0).T        
    y_ku = y_ku.to(torch.int64)        
    self.log('test_auroc', auroc(probs, y_ku), prog_bar=True)        
    return
```

Hope this can help you.
